### PR TITLE
Added exportToOFF(), perturbed duplicate vertices, and modified Range() to be v0.3 compatible

### PR DESCRIPTION
**Pull request by abahm**
I've added a couple of new functions, exportToOFF(), and clean().   I'm not sure why, but the meshes I create with isosurface() generally have some zero-area faces.   clean() removes all zero-area faces and duplicate vertices.  If the isosurface() can be made to do the same thing, perhaps that is better than a post-cleaning step.
I was also trying to run my code against the latest 0.3 Julia, and there was one error with Range() that was blocking.  I changed it so it seems to work in both 0.2 and 0.3.

### CODE REVIEW

**Comment by twadleigh** [comment]
If your extraction isn't careful, zero-area degeneracies can occur when the value of your lsf is exactly equal to the isovalue at a voxel corner. There are at least three things that can be done to avoid it:
1. Preprocess your lsf to perturb it away from the isovalue on the grid.
2. Implicitly perform an analogous perturbation during extraction. The mesh vertices lie on line segments joining voxel corners. Forcing the vertex coordinate to be bounded away from either end of the segment would achieve a similar effect. My implementation at work does this, but I don't remember if my julia version does. Since you claim that you are seeing properly degenerate faces, though, I'm guessing not. It is a simple addition, though. I'll take a look this weekend.
3. Postprocess. Your clean method should do this. (I haven't looked at it yet, but my primary concern would be that it is guaranteed not to change the topological genus of the mesh.) Also, mesh simplification, should I ever get that working, would also hopefully be able to do this.

In light of this, consider whether you think it is worth keeping clean regardless, or whether (2) by itself would answer the mail as far as your concerned.

On the simplification front: last weekend I started to look at it again. I started off with what I thought would be a quick little clean-up task in the ImmutableArrays package (a dependency of Meshes). That turned into a somewhat involved search for a bug that now looks like it lies somewhere in LLVM (and is therefore well beyond my capabilities to address). Anyway, I'm getting close to being done with what I need to do with that effort and will soon be ready to look at Meshes proper again.

**Comment by twadleigh** [comment]
I just checked, and I _did not_ implement (2) above. Here is a simple patch for that, though:

```
diff --git a/src/isosurface.jl b/src/isosurface.jl
index e876408..24795ff 100644
--- a/src/isosurface.jl
+++ b/src/isosurface.jl
@@ -162,6 +162,8 @@ function vertPos{T<:Real}(e::Int64, x::Int64, y::Int64, z::Int64,
     srcVal = float(vals[ixs[1]])
     tgtVal = float(vals[ixs[2]])
     a = (float(iso)-srcVal)/(tgtVal-srcVal)
+    const EPS = 0.001
+    a = min(max(a,EPS),1.0-EPS)
     b = 1.0-a
     org = float([x,y,z])
     src = org+float(voxCrnrPos[:,ixs[1]])
```

If you can, would add this to an amended pull request? I would also really appreciate it if you could take a moment to verify whether or not it addresses any or all of the degeneracies that you were seeing.

Thanks for your contributions.

**Comment by abahm** [comment]
Thanks for the patch - I've applied it, and that also fixed another symptom in meshes I was generating.  I've removed the clean() function.

**Comment by abahm** [comment]
Finally getting back to this, apologies for the delay.  I think everything is now taken care of?  I'm re-submitting a pull request.

**Comment by SimonDanisch** [comment]
The Range -> range error is still not fixed, is it? 
It gives me an error in isosurfaces.jl line 206

**Comment by abahm** [comment]
I believe that with the last commit (9725755) above on May 8 this is fixed.

**Comment by SimonDanisch** [comment]
Well, this is pretty weird, as the change doesn't seem to be in the master...
That's what's on the master, when I look at it via Github:

```
for i = 1:6
        tIx = tetIx(i,vals,iso)

        for j = Range(1,3,2)
            e1 = tetTri[j,tIx]
            e2 = tetTri[j+1,tIx]
            e3 = tetTri[j+2,tIx]

            # bail if there are no more faces
            if e1 == 0 break end

            # add the face to the list
            vId(e) = getVertId(voxEdgeId(i,e),x,y,z,nx,ny,vals,iso,vts)
            push!(fcs,Face(vId(e1),vId(e2),vId(e3)))
        end
    end
```

**Comment by twadleigh** [comment]
There is a pending pull request. I'll merge it into master when I can (some
time this evening).

**Comment by twadleigh** [comment]
Sorry it took so long to merge this. No reason other than it just fell of my radar screen for a while. Thanks for the contribution.

I've bumped the tag and submitted the corresponding pull request to METADATA.jl.

**Pull request merged**
