### PR TITLE
MeshIO Integration

### PR DESCRIPTION
**Pull request by sjkelly**

### CODE REVIEW

**Comment by sjkelly** [comment]
@SimonDanisch I am thinking about removing the dependence on `MeshIO`. This way anything that need file loading or saving needs to go though `FileIO` and `load` and `save` are not magically exported into a project.

**Comment by SimonDanisch** [comment]
The dependency is already completely removed in my PR, I'd say ;)

**Comment by sjkelly** [comment]
Okay. Meshes is going to be pretty thin! I was also thinking of removing `csg.jl` in favor of breaking out https://github.com/sjkelly/Descartes.jl/blob/master/src/frep.jl into a new package that uses GeometryTypes as well.

**Comment by sjkelly** [comment]
@SimonDanisch FYI the tests are failing on this branch (CI is going to fail regardless until FileIO and MeshIO are tagged). I am getting the following backtrace:

```
steve:~/.julia/v0.4/Meshes(sjk/meshio)$ julia ./test/runtests.jl 
INFO: Recompiling stale cache file /home/steve/.julia/lib/v0.4/FileIO.ji for module FileIO.
INFO: Recompiling stale cache file /home/steve/.julia/lib/v0.4/Meshes.ji for module Meshes.
Testing Slice..
INFO: Recompiling stale cache file /home/steve/.julia/lib/v0.4/MeshIO.ji for module MeshIO.
ERROR: LoadError: LoadError: MethodError: `slice` has no method matching slice(::GeometryTypes.HomogenousMesh{FixedSizeArrays.Point{3,Float32},GeometryTypes.Face{3,UInt32,-1},GeometryTypes.Normal{3,Float32},Void,Void,Void,Void}, ::Array{Float64,1})
Closest candidates are:
  slice(!Matched::AbstractArray{T,N}, ::Union{AbstractArray{T,1},Colon,Int64}...)
  slice(!Matched::GeometryTypes.HomogenousMesh{FixedSizeArrays.Point{3,Float64},GeometryTypes.Face{3,Int64,0},NormalT,TexCoordT,ColorT,AttribT,AttribIDT}, ::Array{Float64,1})
  slice(!Matched::GeometryTypes.HomogenousMesh{FixedSizeArrays.Point{3,Float64},GeometryTypes.Face{3,Int64,0},NormalT,TexCoordT,ColorT,AttribT,AttribIDT}, ::Array{Float64,1}, !Matched::Any)
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/steve/.julia/v0.4/Meshes/test/test_slice.jl, in expression starting on line 6
while loading /home/steve/.julia/v0.4/Meshes/test/runtests.jl, in expression starting on line 6
```

**Pull request merged**
