### PR TITLE
Feature/tweak testing

### PR DESCRIPTION
**Pull request by KristofferC**
- Enables testing with `coverage=true` to output the .cov.jl files that `Coverage` uses to send to Coveralls.
- Moves the Lint to the test/REQUIRE file since it isn't strictly needed to run the package.

### CODE REVIEW

**Comment by KristofferC** [comment]
`Lint` seem to fail to initialize in v0.4 causing the test for v0.4 to fail.

``` julia
Warning: error initializing module Lint:
Base.AssertionError(msg="typeof(ex.args[3]) == Symbol")
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: RTLD_GLOBAL not defined
```

Don't really know why...

**Comment by sjkelly** [comment]
This was probably caused by the LibC and LibDL move (https://github.com/JuliaLang/julia/pull/10328)

One alternative I have used is wrap `using Lint; lingpkg();` in `if "--lint" in ARGS` so that lint is only run with `runtests.jl --lint`. I kind of find the lint output annoying after a while and less informative.

Otherwise these changes look good to me! I think you can self-merge, so feel free to do so when you are ready.

**Comment by KristofferC** [comment]
Yeah, maybe there isn't a big point in automatic linting at test unless failing to lint cleanly is considered a test failure.

Should I rebase the branch to squash the commits to a single one?

**Comment by sjkelly** [comment]
rebase and squash might be nice but not nessecary. I was realizing how much I polluted the git history on this repo by working directly on master a couple days ago...

**Comment by sjkelly** [comment]
I am alos seeing the same failure on https://github.com/JuliaGeometry/Meshes.jl/pull/39. I think the best thing to do here is put lint behind a CLI option and not bother running it on travis.

**Pull request merged**
