### PR TITLE
Add exportBinaryStl

### PR DESCRIPTION
**Pull request by dhoegh**
Hi I have used the package for some decent work and I thought I would contribute with an `exportBinaryStl` function. Please correct me if you find anything, I do not usually deal with binary data so I made this as a challenge for my self.

### CODE REVIEW

**Comment by dhoegh** [comment]
Should I resubmit this at `MeshIO.jl`, as it seams to be the future of MeshIO in julia?
cc @SimonDanisch, @KristofferC, @sjkelly

**Comment by SimonDanisch** [comment]
That would be great! Sorry if things are a little messy right now, but we're trying to prototype some nice mesh architecture without much time at hand!
I hope the others agree, that IO shouldn't be part of Meshes. IO will become very big, if support for more and more file types will be added.

**Comment by sjkelly** [comment]
Thanks for doing this! I think this should be in both packages for now until MeshIO is published.

**Comment by SimonDanisch** [comment]
Agreed! Tests will follow ;)

2015-05-23 15:28 GMT+02:00 Steve Kelly notifications@github.com:

**Comment by sjkelly** [comment]
The 0.4 failure is also related to tuples and in a different part of the code.

**Pull request merged**
