### PR TITLE
Update travis to run on release and nightly builds

### PR DESCRIPTION
**Pull request by sjkelly**
This will update .travis.yml to run on release and nightly builds

### CODE REVIEW

**Comment by sjkelly** [comment]
This is contingent on merging #15 since run_tests.jl was renamed to runtests.jl.

**Comment by twadleigh** [comment]
Sorry not to have responded sooner, but I'm currently traveling on
vacation. I should be able to look into it this weekend.

**Comment by sjkelly** [comment]
@twadleigh no worries or rush. Enjoy your vacation!

**Comment by twadleigh** [comment]
@sjkelly #16 causes a Travis failure on releases, even after merging #15. I'm reverting right now. Can you look into it and recommit when ready? I've given you push access to my repo.

**Comment by twadleigh** [comment]
I just took a look at the groups for the first time in a few weeks. I see they are about to tag a 0.3. When that goes final, this problem should go away all by itself, right? In which case, we can merge the existing code without change.

**Comment by sjkelly** [comment]
Yes, I see it is passing on 0.3. It should be a quick fix for 0.2, I think we just need float64() in the correct place. I'll take a look in about a hour. Also, thank you for giving me push access.

**Pull request merged**
