### PR TITLE
Meshes2.0

### PR DESCRIPTION
**Pull request by sjkelly**

### CODE REVIEW

**Comment by sjkelly** [comment]
@SimonDanisch do you think you would be up for rebasing this? Master should now be much more similar to this branch. I've added `Point2/3` and `Face3{T,Idx}` types. The isosurface code in master should be identical minus default indexing at 1 rather than 0. I've added some of the algorithms here as well. Since the Mesh file API is now behind a submodule it should be able to co-exist with FileIO. I want to get GLVisualize using a tagged release of Meshes soon!

**Comment by SimonDanisch** [comment]
Yeah nice! Lets do this :) Might take some time though, as I also need to finish up other stuff.

**Comment by sjkelly** [comment]
#55

**Comment by SimonDanisch** [comment]
I should probably just delete Meshes2.0 alltogether.. I don't see any problem with that.

**Pull request closed without merging**
